config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :images

  root 'homepage#homepage'

  get 'fifties', to: 'images#index50s'

  get 'sixties', to: 'images#index60s'

  get 'seventies', to: 'images#index70s'

  get 'eighties', to: 'images#index80s'

  get 'nineties', to: 'images#index90s'

  get 'twothou', to: 'images#index00s'

  get 'twothouten', to: 'images#index10s'

  get 'homepage', to: 'homepage#homepage'

  get 'images', to: "images#index"

  get 'show', to: 'images#show'

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :picture, PictureUploader

  validates :year, numericality: {greater_than: 1949, less_than: 2016}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.order(created_at: :desc).all
  end

  def index50s
    @images50s = Image.where( year: (1950..1959))
  end

  def index60s
    @images60s = Image.where( year: (1960..1969))
  end

  def index70s
    @images70s = Image.where( year: (1970..1979))
  end

  def index80s
    @images80s = Image.where( year: (1980..1989))
  end

  def index90s
    @images90s = Image.where( year: (1990..1999))
  end

  def index00s
    @images00s = Image.where( year: (2000..2009))
  end

  def index10s
    @images10s = Image.where( year: (2010..2015))
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :url, :description, :year, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/homepage/homepage.html.erb
<div id='sidebar'>

<aside class='navigation'>
	<nav>
		<ul>
          <div class='logo'><strong><li><%= link_to 'Looksee', root_path %></li></strong></div>
          <br>
          <br>
					<% if notice %>
				    <p class="alert alert-success"><%= notice %></p>
				  <% end %>

				  <% if alert %>
				    <p class="alert alert-danger"><%= alert %></p>
				  <% end %>

				  <p class="navbar-text pull-right">
				  <% if user_signed_in? %>
				    Logged in as <strong><%= current_user.email %></strong>.
				    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
				    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
				  <% else %>
				    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
				    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
				  <% end %>


        	<li><%= link_to 'Home', root_path %></li>

            <li>Galleries</li>
            	<ul class='drop'>
            	<li><%= link_to '50s', fifties_path %></li>
            	<li><%= link_to '60s', sixties_path %></li>
            	<li><%= link_to '70s', seventies_path %></li>
              <li><%= link_to '80s', eighties_path %></li>
              <li><%= link_to '90s', nineties_path %></li>
              <li><%= link_to '00s', twothou_path %></li>
              <li><%= link_to '10s', twothouten_path %></li>
            	</ul>
                <br>
                <br>

            <li>Connect with us!</li>
            <br>

            <a href="https://github.com/sofiagarcia/looksee" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/5511439e-087e-4434-a0b3-75732ec4d644.png" border="0" alt=" photo 5511439e-087e-4434-a0b3-75732ec4d644.png"/></a>

            <a href="https://instagram.com/sofiagarcia/" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/05955ac9-16f0-43bd-820a-696f4d87fd86.png" border="0" alt=" photo 05955ac9-16f0-43bd-820a-696f4d87fd86.png"/></a>

        </ul>
	</nav>
</aside>

</div>


<section class="intro">

	<%= link_to images_path do %>
		<%= image_tag "http://i229.photobucket.com/albums/ee313/abyles/0b44a6a4-b2c5-46e4-ad2e-44aa2a115d0a.png" %>
	<% end %>

    <br>

    <h1> About </h1>
			<p>   Looksee is an archive dedicated to the history of computer-generated art. Starting with the first ‘digital abstractions’ from 1950 to Google’s Deep Dream software of today, our mission is to document the interaction between technology and human creativity. We encourage you and the community to contribute meaningful and informative content dedicated to the history of digital art. Feel free to explore our collections for inspiration. Go ahead, take a looksee.</p>
<!-- <<<<<<< HEAD -->
			<!-- <button type="button"><%= link_to 'Explore >', images_path%> </button> -->
<!-- ======= -->
			<%= button_to "Explore >", images_path, method: :get, class: "btn btn-default btn-lg" %>
<!-- >>>>>>> c5ebea6bd0250eb36092b857eecfb8fa888f8ed6 -->
</section>

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<div id='sidebar'>

<aside class='navigation'>
  <nav>
    <ul>
      <div class='logo'><strong><li><%= link_to 'Looksee', root_path %></li></strong></div>
      <br>
      <br>

      <li><%= link_to 'Home', root_path %></li>
        <li>Galleries</li>
              <ul class='drop'>
              <li><%= link_to '50s', fifties_path %></li>
              <li><%= link_to '60s', sixties_path %></li>
              <li><%= link_to '70s', seventies_path %></li>
              <li><%= link_to '80s', eighties_path %></li>
              <li><%= link_to '90s', nineties_path %></li>
              <li><%= link_to '00s', twothou_path %></li>
              <li><%= link_to '10s', twothouten_path %></li>
              </ul>
                <br>
                <br>

            <li>Connect with us!</li>
            <br>

            <a href="https://github.com/sofiagarcia/looksee" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/5511439e-087e-4434-a0b3-75732ec4d644.png" border="0" alt=" photo 5511439e-087e-4434-a0b3-75732ec4d644.png"/></a>

            <a href="https://instagram.com/sofiagarcia/" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/05955ac9-16f0-43bd-820a-696f4d87fd86.png" border="0" alt=" photo 05955ac9-16f0-43bd-820a-696f4d87fd86.png"/></a>

        </ul>
  </nav>
</aside>

</div>



<p id="notice"><%= notice %></p>

<section class="intro">

  <%= link_to root_path do %>
    <%= image_tag "http://i229.photobucket.com/albums/ee313/abyles/0b44a6a4-b2c5-46e4-ad2e-44aa2a115d0a.png" %>
  <% end %>

  <br>

    <h1> Explore </h1>


<table>
  <!-- <thead> -->
    <!-- <tr> -->
      <!-- <th>Title</th> -->
      <!-- <th>Description</th> -->
      <!-- <th>Year</th> -->
      <th colspan="3"></th>
    <!-- </tr> -->
  <!-- </thead> -->

  <tbody>
    <% @images.each do |image| %>
      <tr>

        <%= link_to image do %>
      <div class= "collection_img"  <td><%= image_tag image.picture.url(:preview)  %></td></div>
      <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/index00s.html.erb
<div id='sidebar'>

<aside class='navigation'>
  <nav>
    <ul>
      <div class='logo'><strong><li><%= link_to 'Looksee', root_path %></li></strong></div>
      <br>
      <br>

      <li><%= link_to 'Home', root_path %></li>
        <li>Galleries</li>
              <ul class='drop'>
              <li><%= link_to '50s', fifties_path %></li>
              <li><%= link_to '60s', sixties_path %></li>
              <li><%= link_to '70s', seventies_path %></li>
              <li><%= link_to '80s', eighties_path %></li>
              <li><%= link_to '90s', nineties_path %></li>
              <li><%= link_to '00s', twothou_path %></li>
              <li><%= link_to '10s', twothouten_path %></li>
              </ul>
                <br>
                <br>

            <li>Connect with us!</li>
            <br>

            <a href="https://github.com/sofiagarcia/looksee" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/5511439e-087e-4434-a0b3-75732ec4d644.png" border="0" alt=" photo 5511439e-087e-4434-a0b3-75732ec4d644.png"/></a>

            <a href="https://instagram.com/sofiagarcia/" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/05955ac9-16f0-43bd-820a-696f4d87fd86.png" border="0" alt=" photo 05955ac9-16f0-43bd-820a-696f4d87fd86.png"/></a>

        </ul>
  </nav>
</aside>

</div>


<p id="notice"><%= notice %></p>

<section class="intro">

  <%= link_to root_path do %>
    <%= image_tag "http://i229.photobucket.com/albums/ee313/abyles/0b44a6a4-b2c5-46e4-ad2e-44aa2a115d0a.png" %>
  <% end %>

  <br>

    <h1> 2000s Gallery </h1>


<table>
  <!-- <thead> -->
    <!-- <tr> -->
      <!-- <th>Title</th> -->
      <!-- <th>Description</th> -->
      <!-- <th>Year</th> -->
      <th colspan="3"></th>
    <!-- </tr> -->
  <!-- </thead> -->

  <tbody>
    <% @images00s.each do |image| %>
      <tr>

        <%= link_to image do %>
      <div class= "collection_img"  <td><%= image_tag image.picture.url(:preview)  %></td></div>
      <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/index10s.html.erb
<div id='sidebar'>

<aside class='navigation'>
  <nav>
    <ul>
      <div class='logo'><strong><li><%= link_to 'Looksee', root_path %></li></strong></div>
      <br>
      <br>

      <li><%= link_to 'Home', root_path %></li>
        <li>Galleries</li>
              <ul class='drop'>
              <li><%= link_to '50s', fifties_path %></li>
              <li><%= link_to '60s', sixties_path %></li>
              <li><%= link_to '70s', seventies_path %></li>
              <li><%= link_to '80s', eighties_path %></li>
              <li><%= link_to '90s', nineties_path %></li>
              <li><%= link_to '00s', twothou_path %></li>
              <li><%= link_to '10s', twothouten_path %></li>
              </ul>
                <br>
                <br>

            <li>Connect with us!</li>
            <br>

            <a href="https://github.com/sofiagarcia/looksee" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/5511439e-087e-4434-a0b3-75732ec4d644.png" border="0" alt=" photo 5511439e-087e-4434-a0b3-75732ec4d644.png"/></a>

            <a href="https://instagram.com/sofiagarcia/" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/05955ac9-16f0-43bd-820a-696f4d87fd86.png" border="0" alt=" photo 05955ac9-16f0-43bd-820a-696f4d87fd86.png"/></a>

        </ul>
  </nav>
</aside>

</div>


<p id="notice"><%= notice %></p>

<section class="intro">

  <%= link_to root_path do %>
    <%= image_tag "http://i229.photobucket.com/albums/ee313/abyles/0b44a6a4-b2c5-46e4-ad2e-44aa2a115d0a.png" %>
  <% end %>

  <br>

    <h1> 2010s Gallery </h1>


<table>
  <!-- <thead> -->
    <!-- <tr> -->
      <!-- <th>Title</th> -->
      <!-- <th>Description</th> -->
      <!-- <th>Year</th> -->
      <th colspan="3"></th>
    <!-- </tr> -->
  <!-- </thead> -->

  <tbody>
    <% @images10s.each do |image| %>
      <tr>

        <%= link_to image do %>
      <div class= "collection_img"  <td><%= image_tag image.picture.url(:preview)  %></td></div>
      <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/index50s.html.erb
<div id='sidebar'>

<aside class='navigation'>
  <nav>
    <ul>
      <div class='logo'><strong><li><%= link_to 'Looksee', root_path %></li></strong></div>
      <br>
      <br>

      <li><%= link_to 'Home', root_path %></li>
        <li>Galleries</li>
              <ul class='drop'>
              <li><%= link_to '50s', fifties_path %></li>
              <li><%= link_to '60s', sixties_path %></li>
              <li><%= link_to '70s', seventies_path %></li>
              <li><%= link_to '80s', eighties_path %></li>
              <li><%= link_to '90s', nineties_path %></li>
              <li><%= link_to '00s', twothou_path %></li>
              <li><%= link_to '10s', twothouten_path %></li>
              </ul>
                <br>
                <br>

            <li>Connect with us!</li>
            <br>

            <a href="https://github.com/sofiagarcia/looksee" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/5511439e-087e-4434-a0b3-75732ec4d644.png" border="0" alt=" photo 5511439e-087e-4434-a0b3-75732ec4d644.png"/></a>

            <a href="https://instagram.com/sofiagarcia/" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/05955ac9-16f0-43bd-820a-696f4d87fd86.png" border="0" alt=" photo 05955ac9-16f0-43bd-820a-696f4d87fd86.png"/></a>

        </ul>
  </nav>
</aside>

</div>


<p id="notice"><%= notice %></p>

<section class="intro">

  <%= link_to root_path do %>
    <%= image_tag "http://i229.photobucket.com/albums/ee313/abyles/0b44a6a4-b2c5-46e4-ad2e-44aa2a115d0a.png" %>
  <% end %>

  <br>

    <h1> 1950s Gallery </h1>


<table>
  <!-- <thead> -->
    <!-- <tr> -->
      <!-- <th>Title</th> -->
      <!-- <th>Description</th> -->
      <!-- <th>Year</th> -->
      <th colspan="3"></th>
    <!-- </tr> -->
  <!-- </thead> -->

  <tbody>
     <% @images50s.each do |image| %>
      <tr>

        <%= link_to image do %>
      <div class= "collection_img"  <td><%= image_tag image.picture.url(:preview)  %></td></div>
      <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/index60s.html.erb
<div id='sidebar'>

<aside class='navigation'>
  <nav>
    <ul>
      <div class='logo'><strong><li><%= link_to 'Looksee', root_path %></li></strong></div>
      <br>
      <br>

      <li><%= link_to 'Home', root_path %></li>
        <li>Galleries</li>
              <ul class='drop'>
              <li><%= link_to '50s', fifties_path %></li>
              <li><%= link_to '60s', sixties_path %></li>
              <li><%= link_to '70s', seventies_path %></li>
              <li><%= link_to '80s', eighties_path %></li>
              <li><%= link_to '90s', nineties_path %></li>
              <li><%= link_to '00s', twothou_path %></li>
              <li><%= link_to '10s', twothouten_path %></li>
              </ul>
                <br>
                <br>

            <li>Connect with us!</li>
            <br>

            <a href="https://github.com/sofiagarcia/looksee" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/5511439e-087e-4434-a0b3-75732ec4d644.png" border="0" alt=" photo 5511439e-087e-4434-a0b3-75732ec4d644.png"/></a>

            <a href="https://instagram.com/sofiagarcia/" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/05955ac9-16f0-43bd-820a-696f4d87fd86.png" border="0" alt=" photo 05955ac9-16f0-43bd-820a-696f4d87fd86.png"/></a>

        </ul>
  </nav>
</aside>

</div>


<p id="notice"><%= notice %></p>

<section class="intro">

  <%= link_to root_path do %>
    <%= image_tag "http://i229.photobucket.com/albums/ee313/abyles/0b44a6a4-b2c5-46e4-ad2e-44aa2a115d0a.png" %>
  <% end %>

  <br>

    <h1> 1960s Gallery </h1>


<table>
  <!-- <thead> -->
    <!-- <tr> -->
      <!-- <th>Title</th> -->
      <!-- <th>Description</th> -->
      <!-- <th>Year</th> -->
      <th colspan="3"></th>
    <!-- </tr> -->
  <!-- </thead> -->

  <tbody>
    <% @images60s.each do |image| %>
      <tr>

        <%= link_to image do %>
      <div class= "collection_img"  <td><%= image_tag image.picture.url(:preview)  %></td></div>
      <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/index70s.html.erb
<div id='sidebar'>

<aside class='navigation'>
  <nav>
    <ul>
      <div class='logo'><strong><li><%= link_to 'Looksee', root_path %></li></strong></div>
      <br>
      <br>

      <li><%= link_to 'Home', root_path %></li>
        <li>Galleries</li>
              <ul class='drop'>
              <li><%= link_to '50s', fifties_path %></li>
              <li><%= link_to '60s', sixties_path %></li>
              <li><%= link_to '70s', seventies_path %></li>
              <li><%= link_to '80s', eighties_path %></li>
              <li><%= link_to '90s', nineties_path %></li>
              <li><%= link_to '00s', twothou_path %></li>
              <li><%= link_to '10s', twothouten_path %></li>
              </ul>
                <br>
                <br>

            <li>Connect with us!</li>
            <br>

            <a href="https://github.com/sofiagarcia/looksee" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/5511439e-087e-4434-a0b3-75732ec4d644.png" border="0" alt=" photo 5511439e-087e-4434-a0b3-75732ec4d644.png"/></a>

            <a href="https://instagram.com/sofiagarcia/" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/05955ac9-16f0-43bd-820a-696f4d87fd86.png" border="0" alt=" photo 05955ac9-16f0-43bd-820a-696f4d87fd86.png"/></a>

        </ul>
  </nav>
</aside>

</div>


<p id="notice"><%= notice %></p>

<section class="intro">

  <%= link_to root_path do %>
    <%= image_tag "http://i229.photobucket.com/albums/ee313/abyles/0b44a6a4-b2c5-46e4-ad2e-44aa2a115d0a.png" %>
  <% end %>

  <br>

    <h1> 1970s Gallery </h1>


<table>
  <!-- <thead> -->
    <!-- <tr> -->
      <!-- <th>Title</th> -->
      <!-- <th>Description</th> -->
      <!-- <th>Year</th> -->
      <th colspan="3"></th>
    <!-- </tr> -->
  <!-- </thead> -->

  <tbody>
    <% @images70s.each do |image| %>
      <tr>

        <%= link_to image do %>
      <div class= "collection_img"  <td><%= image_tag image.picture.url(:preview)  %></td></div>
      <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/index80s.html.erb
<div id='sidebar'>

<aside class='navigation'>
  <nav>
    <ul>
      <div class='logo'><strong><li><%= link_to 'Looksee', root_path %></li></strong></div>
      <br>
      <br>

      <li><%= link_to 'Home', root_path %></li>
        <li>Galleries</li>
              <ul class='drop'>
              <li><%= link_to '50s', fifties_path %></li>
              <li><%= link_to '60s', sixties_path %></li>
              <li><%= link_to '70s', seventies_path %></li>
              <li><%= link_to '80s', eighties_path %></li>
              <li><%= link_to '90s', nineties_path %></li>
              <li><%= link_to '00s', twothou_path %></li>
              <li><%= link_to '10s', twothouten_path %></li>
              </ul>
                <br>
                <br>

            <li>Connect with us!</li>
            <br>

            <a href="https://github.com/sofiagarcia/looksee" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/5511439e-087e-4434-a0b3-75732ec4d644.png" border="0" alt=" photo 5511439e-087e-4434-a0b3-75732ec4d644.png"/></a>

            <a href="https://instagram.com/sofiagarcia/" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/05955ac9-16f0-43bd-820a-696f4d87fd86.png" border="0" alt=" photo 05955ac9-16f0-43bd-820a-696f4d87fd86.png"/></a>

        </ul>
  </nav>
</aside>

</div>


<p id="notice"><%= notice %></p>

<section class="intro">

  <%= link_to root_path do %>
    <%= image_tag "http://i229.photobucket.com/albums/ee313/abyles/0b44a6a4-b2c5-46e4-ad2e-44aa2a115d0a.png" %>
  <% end %>

  <br>

    <h1> 1980s Gallery </h1>


<table>
  <!-- <thead> -->
    <!-- <tr> -->
      <!-- <th>Title</th> -->
      <!-- <th>Description</th> -->
      <!-- <th>Year</th> -->
      <th colspan="3"></th>
    <!-- </tr> -->
  <!-- </thead> -->

  <tbody>
    <% @images80s.each do |image| %>
      <tr>

        <%= link_to image do %>
      <div class= "collection_img"  <td><%= image_tag image.picture.url(:preview)  %></td></div>
      <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/index90s.html.erb
<div id='sidebar'>

<aside class='navigation'>
  <nav>
    <ul>
      <div class='logo'><strong><li><%= link_to 'Looksee', root_path %></li></strong></div>
      <br>
      <br>

      <li><%= link_to 'Home', root_path %></li>
        <li>Galleries</li>
              <ul class='drop'>
              <li><%= link_to '50s', fifties_path %></li>
              <li><%= link_to '60s', sixties_path %></li>
              <li><%= link_to '70s', seventies_path %></li>
              <li><%= link_to '80s', eighties_path %></li>
              <li><%= link_to '90s', nineties_path %></li>
              <li><%= link_to '00s', twothou_path %></li>
              <li><%= link_to '10s', twothouten_path %></li>
              </ul>
                <br>
                <br>

            <li>Connect with us!</li>
            <br>

            <a href="https://github.com/sofiagarcia/looksee" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/5511439e-087e-4434-a0b3-75732ec4d644.png" border="0" alt=" photo 5511439e-087e-4434-a0b3-75732ec4d644.png"/></a>

            <a href="https://instagram.com/sofiagarcia/" target="_blank"><img src="http://i229.photobucket.com/albums/ee313/abyles/05955ac9-16f0-43bd-820a-696f4d87fd86.png" border="0" alt=" photo 05955ac9-16f0-43bd-820a-696f4d87fd86.png"/></a>

        </ul>
  </nav>
</aside>

</div>


<p id="notice"><%= notice %></p>

<section class="intro">

  <%= link_to root_path do %>
    <%= image_tag "http://i229.photobucket.com/albums/ee313/abyles/0b44a6a4-b2c5-46e4-ad2e-44aa2a115d0a.png" %>
  <% end %>

  <br>

    <h1> 1990s Gallery </h1>


<table>
  <!-- <thead> -->
    <!-- <tr> -->
      <!-- <th>Title</th> -->
      <!-- <th>Description</th> -->
      <!-- <th>Year</th> -->
      <th colspan="3"></th>
    <!-- </tr> -->
  <!-- </thead> -->

  <tbody>
    <% @images90s.each do |image| %>
      <tr>

        <%= link_to image do %>
      <div class= "collection_img"  <td><%= image_tag image.picture.url(:preview)  %></td></div>
      <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Looksee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Cutive+Mono' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>